# Generated by Django 6.1 on 2026-08-14 01:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestao', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cartao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
            ],
        ),
        migrations.RemoveField(
            model_name='metamensal',
            name='mes_ano',
        ),
        migrations.AlterField(
            model_name='metamensal',
            name='valor',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='pessoa',
            name='nome',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='transacao',
            name='data',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='transacao',
            name='descricao',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='transacao',
            name='tipo',
            field=models.CharField(choices=[('DESPESA', 'Gasto no Cartão'), ('PAGAMENTO', 'Recebi Pagamento')], default='DESPESA', max_length=10),
        ),
        migrations.AddField(
            model_name='transacao',
            name='cartao',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='gestao.cartao'),
        ),
    ]
