# Generated by Django 6.1 on 2026-08-15 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestao', '0002_pessoa_telefone'),
    ]

    operations = [
        migrations.AddField(
            model_name='transacao',
            name='recorrente',
            field=models.BooleanField(default=False),
        ),
    ]
