# Generated by Django 6.1 on 2026-08-14 23:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestao', '0003_conta_cartao_conta_pessoa_conta_transacao_conta'),
    ]

    operations = [
        migrations.AddField(
            model_name='metamensal',
            name='conta',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='gestao.conta'),
        ),
    ]
